#!/usr/bin/env node
/**
 * Kinematic Tally Connector
 *
 * Polls Kinematic for pending Tally voucher jobs, posts the rendered XML to
 * the locally-running Tally (default http://localhost:9000), and reports
 * the resulting Tally voucher IDs back to Kinematic for reconciliation.
 *
 * Run modes:
 *   node index.js          — long-running poller (default 30s cadence)
 *   node index.js --once   — one drain pass, exit (useful for cron / Task Scheduler)
 *
 * Config: `./config.json` next to this file. Generated by the Kinematic
 * dashboard when the admin connects Tally — Download kinematic-tally-config.json
 * and place it here.
 *
 * Requires Node 18+ (uses the built-in fetch). No npm dependencies.
 */

'use strict';

const fs   = require('node:fs');
const path = require('node:path');

const CONFIG_PATH = process.env.KINEMATIC_TALLY_CONFIG
  ? path.resolve(process.env.KINEMATIC_TALLY_CONFIG)
  : path.resolve(__dirname, 'config.json');

const ONCE_MODE  = process.argv.includes('--once');

function loadConfig() {
  if (!fs.existsSync(CONFIG_PATH)) {
    console.error(`[FATAL] Config not found at ${CONFIG_PATH}`);
    console.error(`        Download kinematic-tally-config.json from the Kinematic dashboard`);
    console.error(`        (Distribution → Integrations → your Tally integration) and place it here.`);
    process.exit(1);
  }
  const raw = fs.readFileSync(CONFIG_PATH, 'utf-8');
  const cfg = JSON.parse(raw);
  if (!cfg.polling_endpoint || !cfg.report_endpoint || !cfg.integration_id) {
    console.error(`[FATAL] Config at ${CONFIG_PATH} is missing required fields`);
    console.error(`        Expected: polling_endpoint, report_endpoint, integration_id, agent_secret, tally_url, poll_interval_seconds`);
    process.exit(1);
  }
  return {
    integration_id:        cfg.integration_id,
    agent_secret:          cfg.agent_secret,
    polling_endpoint:      cfg.polling_endpoint,
    report_endpoint:       cfg.report_endpoint,
    tally_url:             cfg.tally_url             || 'http://localhost:9000',
    poll_interval_seconds: cfg.poll_interval_seconds || 30,
  };
}

// ── Tally response parsing ─────────────────────────────────────────────────
// Tally's import response looks roughly like:
//   <RESPONSE>
//     <CREATED>1</CREATED>
//     <ALTERED>0</ALTERED>
//     <DELETED>0</DELETED>
//     <LASTVCHID>123</LASTVCHID>
//     <LASTMID>0</LASTMID>
//     <COMBINED>0</COMBINED>
//     <IGNORED>0</IGNORED>
//     <ERRORS>0</ERRORS>
//   </RESPONSE>
//
// Or, on error, contains LINEERROR / DESC fields with the human-readable
// problem.
function parseTallyResponse(xml) {
  const tag = (name) => {
    const m = xml.match(new RegExp(`<${name}>([^<]*)</${name}>`, 'i'));
    return m ? m[1].trim() : null;
  };
  const created = parseInt(tag('CREATED') || '0', 10);
  const errors  = parseInt(tag('ERRORS')  || '0', 10);
  const lastVchId = tag('LASTVCHID');
  const lineError = tag('LINEERROR') || tag('DESC');
  if (errors > 0 || (created === 0 && lineError)) {
    return { ok: false, error: lineError || 'Tally rejected the voucher' };
  }
  if (created < 1 && !lastVchId) {
    return { ok: false, error: 'Tally accepted the request but created 0 vouchers' };
  }
  return { ok: true, tally_voucher_id: lastVchId || undefined };
}

// ── Network helpers ─────────────────────────────────────────────────────────
async function fetchJobs(cfg) {
  const res = await fetch(cfg.polling_endpoint, { method: 'GET' });
  if (!res.ok) throw new Error(`Kinematic poll returned HTTP ${res.status}`);
  const json = await res.json();
  if (!json.ok) throw new Error(`Kinematic poll error: ${json.error || 'unknown'}`);
  return json.jobs || [];
}

async function postToTally(cfg, xml) {
  const res = await fetch(cfg.tally_url, {
    method: 'POST',
    headers: { 'Content-Type': 'text/xml; charset=utf-8' },
    body: xml,
  });
  const body = await res.text();
  if (!res.ok) {
    return { ok: false, error: `Tally HTTP ${res.status}: ${body.slice(0, 300)}` };
  }
  return parseTallyResponse(body);
}

async function reportResult(cfg, event_id, ok, tally_voucher_id, error) {
  const res = await fetch(cfg.report_endpoint, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({ event_id, ok, tally_voucher_id, error }),
  });
  if (!res.ok) {
    console.error(`[WARN] Result report returned HTTP ${res.status} for event ${event_id}`);
  }
}

// ── Main loop ───────────────────────────────────────────────────────────────
async function drainOnce(cfg) {
  let jobs;
  try {
    jobs = await fetchJobs(cfg);
  } catch (e) {
    console.error(`[ERROR] fetchJobs failed: ${e.message}`);
    return 0;
  }
  if (jobs.length === 0) return 0;
  console.log(`[${new Date().toISOString()}] processing ${jobs.length} job(s)`);

  for (const job of jobs) {
    const start = Date.now();
    let result;
    try {
      result = await postToTally(cfg, job.xml_payload);
    } catch (e) {
      result = { ok: false, error: `Tally connection failed: ${e.message}` };
    }
    const elapsed = Date.now() - start;
    if (result.ok) {
      console.log(`  ✓ ${job.kind} ${job.ref_id} → Tally voucher ${result.tally_voucher_id || '(no id)'} (${elapsed}ms)`);
    } else {
      console.log(`  ✗ ${job.kind} ${job.ref_id} → ${result.error} (${elapsed}ms)`);
    }
    try {
      await reportResult(cfg, job.event_id, result.ok, result.tally_voucher_id, result.error);
    } catch (e) {
      console.error(`[ERROR] reportResult failed for event ${job.event_id}: ${e.message}`);
    }
  }
  return jobs.length;
}

async function main() {
  const cfg = loadConfig();

  console.log(`Kinematic Tally Connector`);
  console.log(`  integration_id: ${cfg.integration_id}`);
  console.log(`  tally_url:      ${cfg.tally_url}`);
  console.log(`  cadence:        ${cfg.poll_interval_seconds}s${ONCE_MODE ? ' (--once, exiting after first drain)' : ''}`);
  console.log('');

  if (ONCE_MODE) {
    await drainOnce(cfg);
    process.exit(0);
  }

  // Long-running mode: drain immediately, then on interval. setInterval is
  // simpler than a recursive setTimeout because drainOnce is awaited inside
  // the same async function context.
  let busy = false;
  const tick = async () => {
    if (busy) return; // skip if the previous drain is still running
    busy = true;
    try { await drainOnce(cfg); } finally { busy = false; }
  };
  await tick();
  setInterval(tick, cfg.poll_interval_seconds * 1000);

  // Clean shutdown on Ctrl-C / SIGTERM (Windows Service stop).
  for (const sig of ['SIGINT', 'SIGTERM']) {
    process.on(sig, () => {
      console.log(`\nReceived ${sig}, shutting down…`);
      process.exit(0);
    });
  }
}

main().catch(e => {
  console.error(`[FATAL] ${e.stack || e.message || e}`);
  process.exit(1);
});
